name: patrol_ttrpg_manager
description: A tactical character generator for TTRPGs.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Typography
  google_fonts: ^6.1.0        # For 'Share Tech Mono' and Stencil proxies
  flutter_animate: ^4.5.0     # For CRT turn-on effects and UI glides
  font_awesome_flutter: ^10.6.0 # For tactical icons (crosshairs, gears)

  # State Management & Logic
  provider: ^6.1.1            # Simple state management for the "Soldier Engine"
  uuid: ^4.2.1                # Unique IDs for characters
  intl: ^0.20.2               # Date formatting for "Service Records"

  # Data Persistence (Local First)
  shared_preferences: ^2.2.2  # Simple key-value storage for settings
  path_provider: ^2.1.1       # To find where to save the JSON dossiers
  json_annotation: ^4.8.1     # For serializing character data
  pdf: ^3.10.0
  printing: ^5.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

dependency_overrides:
  characters: 1.4.1
  lints: 6.0.0
  matcher: 0.12.18
  material_color_utilities: 0.13.0
  test_api: 0.7.8
  

flutter:
  uses-material-design: true

  # Asset Pipeline: Place your acrylic textures and local fonts here
  # assets:
  #   - assets/images/textures/ # For canvas_grain.png
  #   - assets/images/ranks/    # For rank_insignia.png
  #   - assets/images/paper_doll/
